# version: "3.9"
# services:
#   wize-dashboard-monitor-api:
#     image: rg.fr-par.scw.cloud/my-namespace/bewize-dashboard-monitor-api:latest
#     container_name: wize-dashboard-monitor-api
#     environment:
#       # Set active profile and app port
#       SPRING_PROFILES_ACTIVE: production
#       SERVER_PORT: 4001
#       JAVA_OPTS: -Xms256m -Xmx512m
#     ports:
#       - "4001:8080"
#     restart: unless-stopped

version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: bewize-dashboard-monitor-postgres
    environment:
      POSTGRES_DB: bewize_dm_dev
      POSTGRES_USER: bewize
      POSTGRES_PASSWORD: bewize
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bewize"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
