spring.datasource.url=jdbc:postgresql://localhost:5432/bewize_dm_dev
spring.datasource.username=bewize
spring.datasource.password=bewize
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=http://localhost:3000
