spring.datasource.url=jdbc:postgresql://localhost:5432/bewize_dm_dev
spring.datasource.username=bewize
spring.datasource.password=bewize
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS - localhost pour dev local + Netlify pour production
app.cors.allowed-origins=http://localhost:5173,https://abdelhamid0p.github.io/bewize-dashboard-monitor/

# Actuator - healthcheck endpoint
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
